name: Manual Canary Build

on:
  workflow_dispatch: # 仅允许手动触发

jobs:
  build-canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          repository: innei/shiro
          ref: main # 假设主分支为 main，根据实际情况修改
          fetch-depth: 0 # 获取完整提交历史
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate canary tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shiro-canary
          tags: |
            type=raw,value=canary
            type=raw,value=latest-$(date +%Y%m%d)
            type=sha,prefix=,suffix=-canary

      - name: Build and push canary
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print image info
        run: |
          echo "Successfully built canary images:"
          echo "${{ steps.meta.outputs.tags }}"
